spring:
  datasource:
    username: postgres
    password: lol
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://structuremade.de:5432/structuremade
  jpa:
    show-sql: on
    generate-ddl: on
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: services
  application:
    name: AUTHSERVICE
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka.structuremade.de/eureka/
server:
  port: 80

